//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class 優惠明細CouponLists
    {
        public int 優惠明細編號CouponList_ID { get; set; }
        public int 會員編號Member_ID { get; set; }
        public int 優惠編號Coupon_ID { get; set; }
        public bool 是否使用優惠OX_CouponUsing { get; set; }
    
        public virtual 會員Members 會員Members { get; set; }
        public virtual 優惠總表Coupon 優惠總表Coupon { get; set; }
    }
}
