//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class 電影代碼MovieCode
    {
        public int 電影代碼Movie_Code { get; set; }
        public int 電影編號Movie_ID { get; set; }
        public int 語言編號Language_ID { get; set; }
    
        public virtual 電影Movies 電影Movies { get; set; }
        public virtual 電影語言MovieLanguage 電影語言MovieLanguage { get; set; }
    }
}
